version: '3.8'
services:
  postgres:
    image: postgres:12.19-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: library
    ports:
      - "5432:5432"
  
  app:
    image: ahmedelkady513/librarymanagement:latest
    container_name: LibraryManagment
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
